# Generated by Django 3.0.3 on 2020-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.IntegerField(max_length=30)),
                ('Employee_email', models.CharField(max_length=50)),
                ('S_name', models.CharField(max_length=30)),
                ('s_job_pos', models.CharField(max_length=30)),
                ('s_phone', models.IntegerField(max_length=20)),
                ('s_address', models.CharField(max_length=100)),
                ('what_wrong', models.TextField()),
                ('who_wrong', models.TextField()),
                ('where_wrong', models.TextField()),
                ('enabled_wrong', models.TextField()),
                ('solution', models.TextField()),
                ('incident_date', models.DateField()),
            ],
        ),
    ]
