# Generated by Django 3.0.3 on 2020-03-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhistleBlower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='documents',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='Employee_Id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='s_phone',
            field=models.IntegerField(),
        ),
    ]
