# Generated by Django 3.0.3 on 2020-03-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhistleBlower', '0002_auto_20200302_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
